"""create normalized report schema

Revision ID: 88eb23782b4a
Revises: 
Create Date: 2026-05-30 02:04:39.499417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88eb23782b4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('source_format', sa.String(length=32), nullable=False),
    sa.Column('processing_status', sa.String(length=64), nullable=False),
    sa.Column('storage_mode', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_owner_user_id'), 'documents', ['owner_user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('document_sections',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('section_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('position_in_document', sa.Integer(), nullable=False),
    sa.Column('section_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_sections_document_id'), 'document_sections', ['document_id'], unique=False)
    op.create_table('processing_sessions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_sessions_document_id'), 'processing_sessions', ['document_id'], unique=False)
    op.create_index(op.f('ix_processing_sessions_owner_user_id'), 'processing_sessions', ['owner_user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=True),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('processing_session_id', sa.String(length=128), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('summary_status', sa.String(length=64), nullable=False),
    sa.Column('total_issues', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('major_count', sa.Integer(), nullable=False),
    sa.Column('minor_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processing_session_id'], ['processing_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_document_id'), 'reports', ['document_id'], unique=False)
    op.create_index(op.f('ix_reports_owner_user_id'), 'reports', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_reports_processing_session_id'), 'reports', ['processing_session_id'], unique=False)
    op.create_table('checks',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('processing_session_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=True),
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('model_or_ruleset_version', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processing_session_id'], ['processing_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checks_document_id'), 'checks', ['document_id'], unique=False)
    op.create_index(op.f('ix_checks_processing_session_id'), 'checks', ['processing_session_id'], unique=False)
    op.create_index(op.f('ix_checks_report_id'), 'checks', ['report_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('check_id', sa.String(length=160), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('issue_type', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_fragment', sa.Text(), nullable=True),
    sa.Column('source_agent', sa.String(length=128), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('issue_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_check_id'), 'issues', ['check_id'], unique=False)
    op.create_index(op.f('ix_issues_document_id'), 'issues', ['document_id'], unique=False)
    op.create_index(op.f('ix_issues_issue_type'), 'issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_issues_report_id'), 'issues', ['report_id'], unique=False)
    op.create_index(op.f('ix_issues_severity'), 'issues', ['severity'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('issue_id', sa.String(length=160), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('example_fix', sa.Text(), nullable=True),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_issue_id'), 'recommendations', ['issue_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_issue_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_issues_severity'), table_name='issues')
    op.drop_index(op.f('ix_issues_report_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_issue_type'), table_name='issues')
    op.drop_index(op.f('ix_issues_document_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_check_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_checks_report_id'), table_name='checks')
    op.drop_index(op.f('ix_checks_processing_session_id'), table_name='checks')
    op.drop_index(op.f('ix_checks_document_id'), table_name='checks')
    op.drop_table('checks')
    op.drop_index(op.f('ix_reports_processing_session_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_owner_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_document_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_processing_sessions_owner_user_id'), table_name='processing_sessions')
    op.drop_index(op.f('ix_processing_sessions_document_id'), table_name='processing_sessions')
    op.drop_table('processing_sessions')
    op.drop_index(op.f('ix_document_sections_document_id'), table_name='document_sections')
    op.drop_table('document_sections')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_documents_owner_user_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
